version: '3.7'
services:
  db:
    image: postgres:10.5-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3008:3000"
    depends_on:
      - db
    volumes:
      - .:/app
    workdir:
      - /app