default: &default
  adapter: postgresql
  host: <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  encoding: unicode
  min_messages: warning
  pool: 2
  timeout: 5000
  
development:
  <<: *default
  database: 2network_development
  
test:
  <<: *default
  database: 2network_test

production:
  <<: *default
  database: hours_production